/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.UUID;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.TicketBookingService;
// import org.example.services.TrainService;
import org.example.util.UserServiceUtil;

public class App {
    public static void main(String[] args) {
        System.out.println("Running Train Booking Sytem");
        Scanner scanner = new Scanner(System.in);

        int option = 0;

        TicketBookingService ticketBookingService;

        try {
            ticketBookingService = new TicketBookingService();
        } catch (IOException ex) {
            ex.printStackTrace();
            scanner.close();
            return;
        }

        while (option != 7) {
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();
            Train trainSelectedForBooking = new Train();
            switch (option) {
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();

                    User userToSignUp = new User(nameToSignUp, passwordToSignUp,
                            UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(),
                            UUID.randomUUID().toString());

                    ticketBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter the username to login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter the password to login");
                    String passwordToLogin = scanner.next();

                    User userToLogin = new User(nameToLogin, passwordToLogin,
                            UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(),
                            UUID.randomUUID().toString());

                    try {
                        ticketBookingService = new TicketBookingService(userToLogin);
                    } catch (IOException ex) {
                        return;
                    }
                    break;

                case 3:
                    System.out.println("Fetching your bookings");
                    ticketBookingService.fetchBooking();
                    break;

                case 4:
                    List<Train> allTrains = ticketBookingService.getAllTrains();
                    // Better: create a getAllTrains() method, but using this for now

                    if (allTrains.isEmpty()) {
                        System.out.println("No trains available.");
                        break;
                    }

                    // 1️⃣ List all trains
                    System.out.println("Available trains:");
                    for (int i = 0; i <= allTrains.size(); i++) {
                        System.out.println((i + 1) + ". Train Station: " + allTrains.get(i).getStations());
                    }

                    System.out.println("Select a train:");
                    int trainChoice = scanner.nextInt() - 1;

                    if (trainChoice < 0 || trainChoice >= allTrains.size()) {
                        System.out.println("Invalid train selection");
                        break;
                    }

                    trainSelectedForBooking = allTrains.get(trainChoice);

                    // 2️⃣ List stations of selected train
                    List<String> stations = trainSelectedForBooking.getStations();
                    Map<String, String> timings = trainSelectedForBooking.getStationTimes();

                    System.out.println("Stations in this train:");
                    for (int i = 0; i < stations.size(); i++) {
                        String station = stations.get(i);
                        System.out.println((i + 1) + ". " + station + " (" + timings.get(station) + ")");
                    }

                    // 3️⃣ Select source station
                    System.out.println("Select source station:");
                    int sourceIndex = scanner.nextInt() - 1;

                    if (sourceIndex < 0 || sourceIndex >= stations.size()) {
                        System.out.println("Invalid source station");
                        break;
                    }

                    String sourceStation = stations.get(sourceIndex);

                    // 4️⃣ Select destination station (only after source)
                    System.out.println("Select destination station:");
                    for (int i = sourceIndex + 1; i < stations.size(); i++) {
                        System.out.println((i + 1) + ". " + stations.get(i));
                    }

                    int destinationIndex = scanner.nextInt() - 1;

                    if (destinationIndex <= sourceIndex || destinationIndex >= stations.size()) {
                        System.out.println("Invalid destination station");
                        break;
                    }

                    String destinationStation = stations.get(destinationIndex);

                    System.out.println("Selected Train: " + trainSelectedForBooking.getTrainId());
                    System.out.println("From: " + sourceStation);
                    System.out.println("To: " + destinationStation);

                    break;

                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = ticketBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row : seats) {
                        for (Integer val : row) {
                            System.out.print(val + " ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = scanner.nextInt();
                    System.out.println("Enter the column");
                    int col = scanner.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = ticketBookingService.bookTrainSeat(trainSelectedForBooking, row, col);
                    if (booked.equals(Boolean.TRUE)) {
                        System.out.println("Booked! Enjoy your journey");
                    } else {
                        System.out.println("Can't book this seat");
                    }
                    break;

                case 6:
                    System.out.println("Enter your Ticket ID");
                    String TicketIdForCancel = scanner.next();

                    System.out.println("Cancelling your ticket...");
                    ticketBookingService.cancelBooking(TicketIdForCancel);

                    System.out.println("Your ticket with ID-" + TicketIdForCancel + " is cancelled");

                default:
                    break;
            }
        }
        scanner.close();
    }
}
