/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.UUID;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.TicketBookingService;
import org.example.services.TrainService;
import org.example.util.UserServiceUtil;

public class App {
    public static void main(String[] args) {
        System.out.println("Running Train Booking Sytem");
        Scanner scanner = new Scanner(System.in);

        int option = 0;

        TicketBookingService ticketBookingService;
        TrainService trainService;

        try {
            trainService = new TrainService();
        } catch (IOException ex) {
            ex.printStackTrace();
            scanner.close();
            return;
        }

        try {
            ticketBookingService = new TicketBookingService();
        } catch (IOException ex) {
            ex.printStackTrace();
            scanner.close();
            return;
        }

        while (option != 7) {
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();

            switch (option) {
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();

                    User userToSignUp = new User(nameToSignUp, passwordToSignUp,
                            UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(),
                            UUID.randomUUID().toString());

                    ticketBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter the username to login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter the password to login");
                    String passwordToLogin = scanner.next();

                    User userToLogin = new User(nameToLogin, passwordToLogin,
                            UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(),
                            UUID.randomUUID().toString());

                    try {
                        ticketBookingService = new TicketBookingService(userToLogin);
                    } catch (IOException ex) {
                        return;
                    }
                    break;

                case 3:
                    System.out.println("Fetching your bookings");
                    ticketBookingService.fetchBooking();
                    break;

                case 4:
                    List<Train> allTrains = ticketBookingService.getAllTrains();

                    if (allTrains.isEmpty()) {
                        System.out.println("No trains available.");
                        break;
                    }

                    System.out.println("Available stations:");
                    allTrains.stream()
                            .flatMap(train -> train.getStations().stream())
                            .distinct()
                            .forEach(station -> System.out.println("- " + station));

                    scanner.nextLine();

                    System.out.print("Enter source station: ");
                    String source = scanner.nextLine().trim().toLowerCase();

                    System.out.print("Enter destination station: ");
                    String destination = scanner.nextLine().trim().toLowerCase();

                    List<Train> availableTrains = trainService.searchTrains(source, destination);

                    if (availableTrains.isEmpty()) {
                        System.out.println("No trains available for this route.");
                        break;
                    }

                    System.out.println("\nAvailable trains:");
                    for (Train train : availableTrains) {
                        System.out.println(
                                "Train ID: " + train.getTrainId() +
                                " | Departure: " + train.getStationTimes().get(source) +
                                " | Arrival: " + train.getStationTimes().get(destination)
                            );
                    }

                    break;

                case 5:
                    scanner.nextLine(); 

                    System.out.print("Enter Train ID to book seat: ");
                    String trainIdInput = scanner.nextLine().trim();

                    Train selectedTrain = ticketBookingService.getAllTrains()
                            .stream()
                            .filter(t -> t.getTrainId().equalsIgnoreCase(trainIdInput))
                            .findFirst()
                            .orElse(null);

                    if (selectedTrain == null) {
                        System.out.println("Invalid Train ID. Please search trains first.");
                        break;
                    }

                    System.out.print("Enter date of travel (YYYY-MM-DD): ");
                    String dateOfTravel = scanner.nextLine().trim();

                    List<List<Integer>> seats = ticketBookingService.fetchSeats(selectedTrain);

                    System.out.println("\nSeat Layout");
                    System.out.println("0 = Available | 1 = Booked");
                    System.out.println("Row = horizontal | Column = vertical\n");

                    System.out.print("     ");
                    for (int c = 0; c < seats.get(0).size(); c++) {
                        System.out.print(c + " ");
                    }
                    System.out.println();

                    for (int r = 0; r < seats.size(); r++) {
                        System.out.print("Row " + r + "  ");
                        for (int c = 0; c < seats.get(r).size(); c++) {
                            System.out.print(seats.get(r).get(c) + " ");
                        }
                        System.out.println();
                    }

                    System.out.print("\nEnter row number: ");
                    int row = scanner.nextInt();

                    System.out.print("Enter column number: ");
                    int col = scanner.nextInt();

                    String sourceStation = selectedTrain.getStations().get(0); 
                    String destinationStation = selectedTrain.getStations().get(selectedTrain.getStations().size() - 1); 

                    System.out.println("Booking your seat...");

                    Boolean booked = ticketBookingService.bookTrainSeat(
                            selectedTrain,
                            row,
                            col,
                            sourceStation,
                            destinationStation,
                            dateOfTravel);

                    if (Boolean.TRUE.equals(booked)) {
                        System.out.println("Seat booked successfully 🎉");
                    } else {
                        System.out.println("Seat already booked or invalid position.");
                    }

                    break;

                case 6:
                    System.out.println("Enter your Ticket ID");
                    String TicketIdForCancel = scanner.next();

                    System.out.println("Cancelling your ticket...");
                    ticketBookingService.cancelBooking(TicketIdForCancel);

                    System.out.println("Your ticket with ID-" + TicketIdForCancel + " is cancelled");

                default:
                    break;
            }
        }
        scanner.close();
    }
}
